### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by webysther** [SimplePDF/simplepdf-embed#1]
- Support add free shape like ilovepdf
- Maybe integrate to https://github.com/Frooodle/Stirling-PDF/issues/165

**Comment by bendersej** [comment]
Hey @webysther!

> Support add free shape like ilovepdf

While I don't want to completely discard the idea, I wish to focus _for now_ on the core use of SimplePDF: filling PDF documents.

> Maybe integrate to https://github.com/Frooodle/Stirling-PDF/issues/165

Thanks for the ping! I posted a message over there

**Comment by webysther** [comment]
Actually we use the signuture box for this putting a small dot, the problem is the box is not frelly resizible, the ratio is fixed, if this is changed the feature is ready, if you create a option to change the background color you get this done.

**Comment by bendersej** [comment]
> Actually we use the signuture box for this putting a small dot, the problem is the box is not frelly resizible, the ratio is fixed, if this is changed the feature is ready, if you create a option to change the background color you get this done.

Even if the ratio is fixed, the proportions are kept, so adding a small dot should work!

As for changing the background colour, this is something that I have in the backlog

Closing the issue, I'll let you know once the background colour change is out, @webysther
