### ISSUE TITLE
hi I accidently submitted my personal info through this tool

### ISSUE THREAD

**Issue by zc3721** [SimplePDF/simplepdf-embed#2]
If you guys saw it, please not use it and help me to delete it
Thank you

**Comment by bendersej** [comment]
Hey @zc3721!

Can you send me an email over here: bonjour@simplepdf.eu and include:
1. The email (if you specified one when sending the file)
2. The time around which you sent the file

I'll use both of these and remove all upload files during that time period!

Have a great day!

Benjamin
