### ISSUE TITLE
window.simplePDF.openEditor always opens "choose from your computer" instead of specified PDF URL

### ISSUE THREAD

**Issue by jtlocsei** [SimplePDF/simplepdf-embed#6]
Hi, this tool looks amazing and thanks so much for creating it, but when I run `window.simplePDF.openEditor({ url: "publicly_available_url_pdf" }); ` from the console (with a real PDF URL) then I still always get the "Select PDF from your computer" button. Any tips? Thanks!

**Comment by bendersej** [comment]
Hey @jtlocsei!

Thank you so much for taking the time to raise this issue!

The documentation was incorrect and the correct parameter is `href` (and not `url`) as visible below:

```
window.simplePDF.openEditor({ href: "publicly_available_url_pdf" });
```

[I updated the documentation in this commit](https://github.com/SimplePDF/simplepdf-embed/commit/a33b996253bf8c2df1ae6f6b051cf8c51783cea3)
