### ISSUE TITLE
How to use non roman languages to edit  

### ISSUE THREAD

**Issue by Jeevi10** [SimplePDF/simplepdf-embed#7]

**Comment by bendersej** [comment]
Hey @Jeevi10!

What languages would you like SimplePDF to support?

Currently, on top of Roman alphabet languages, Cyrillic alphabet ones, Chinese, Turkish, Serbian, Greek, Turkish are also supported (among others)

**Comment by Jeevi10** [comment]
Hi @bendersej , 
Thank you for your prompt reply, I was trying to use Tamil (native language). It would be greatly appreciated if you could add the support for it.  I have seen many struggling to edit pdfs in Tamil unless they have Adobe pro.

**Comment by bendersej** [comment]
Hey @Jeevi10!

Your suggestion prompted me to add support both for Tamil and Hindi!

It's now live, let me know if you run into any issues! I tested thoroughly but as I'm not a speaker of neither, I wasn't able to confirm that the editing experience was as good as possible

If you want to help spread the word, you can like / retweet the announcement on X: https://x.com/simple_pdf/status/1816160682485707010
